#ifndef SAKLIB_INTERNAL_PROPERTIES_NAME__INLINE_H
#define SAKLIB_INTERNAL_PROPERTIES_NAME__INLINE_H

#ifndef SAKLIB_INTERNAL_PROPERTIES_NAME_H
#include "name.h"
#endif

#endif // SAKLIB_INTERNAL_PROPERTIES_NAME__INLINE_H

