#ifndef SAKLIB_INTERNAL_ALL_UNDOABLE_ATTRIBUTE_DATA_HANDLE__FWD_H
#define SAKLIB_INTERNAL_ALL_UNDOABLE_ATTRIBUTE_DATA_HANDLE__FWD_H

#ifndef SAKLIB_INTERNAL_UNDOABLE_ATTRIBUTE_DATA_HANDLE__FWD_H
#include "undoable_attribute_data_handle__fwd.h"
#endif

#ifndef SAKLIB_INTERNAL_UNDOABLE_ATTRIBUTE_DATA_HANDLE_BOOL__FWD_H
#include "undoable_attribute_data_handle_bool__fwd.h"
#endif

#ifndef SAKLIB_INTERNAL_UNDOABLE_ATTRIBUTE_DATA_HANDLE_INT__FWD_H
#include "undoable_attribute_data_handle_int__fwd.h"
#endif

#endif // SAKLIB_INTERNAL_ALL_UNDOABLE_ATTRIBUTE_DATA_HANDLE__FWD_H

