#ifndef SAKLIB_INTERNAL_ATTRIBUTE_DATA_HANDLE__INLINE_H
#define SAKLIB_INTERNAL_ATTRIBUTE_DATA_HANDLE__INLINE_H

#ifndef SAKLIB_INTERNAL_ATTRIBUTE_DATA_HANDLE_H
#include "attribute_data_handle.h"
#endif


#endif // SAKLIB_INTERNAL_ATTRIBUTE_DATA_HANDLE__INLINE_H

